### ISSUE TITLE
Failed to use docker omnidb

### ISSUE THREAD

**Issue by camjoex** [taivokasper/docker-omnidb#1]
Hello 
I'm trying to use your setup docker omnidb but some errors occured.

Step 1:  [ok]
docker pull taivokasper/omnidb 

Step 2: [Failed] 
docker run -it --rm -p 8080:8080 taivokasper/omnidb
```
/usr/local/lib/python3.5/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Starting OmniDB server...
Checking port availability...
Starting server at port 8080.
User database version 2.4.1 is already matching server version.
Press Ctrl+C to exit.
[07/06/2018 13:49:23] ERROR [OmniDB_app.QueryServer:360] *** Exception ***
Traceback (most recent call last):
  File "/opt/OmniDB-2.4.1/OmniDB/OmniDB/ws_core.py", line 356, in start_wsserver
    server.listen(settings.OMNIDB_PORT)
  File "/usr/local/lib/python3.5/dist-packages/tornado/tcpserver.py", line 145, in listen
    self.add_sockets(sockets)
  File "/usr/local/lib/python3.5/dist-packages/tornado/tcpserver.py", line 159, in add_sockets
    sock, self._handle_connection)
  File "/usr/local/lib/python3.5/dist-packages/tornado/netutil.py", line 219, in add_accept_handler
    io_loop = IOLoop.current()
  File "/usr/local/lib/python3.5/dist-packages/tornado/ioloop.py", line 283, in current
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.5/asyncio/events.py", line 671, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "/usr/lib/python3.5/asyncio/events.py", line 583, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-1'.

```
Service exposed on port 8080 but not  working.
Any ideas ?

**Comment by taivokasper** [comment]
No I have no ideas yet but I know the container did work a couple of months back.

Would you be interested in figuring out what's up and submitting a pull request?

**Comment by taivokasper** [comment]
This is fixed now.
